import './globals.css'
import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import { Providers } from './providers'
import { AppLayout } from '@/components/layouts'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark text-foreground bg-background">
      <body className={`${manrope.className}`}>
        <Providers>
          <AppLayout>{children}</AppLayout>
        </Providers>
      </body>
    </html>
  )
}
